# Generated by Django 4.2.6 on 2023-10-22 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('about_course', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('lesson_id', models.IntegerField(primary_key=True, serialize=False)),
                ('lesson_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.courses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.IntegerField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=500)),
                ('true_answer', models.CharField(max_length=300)),
                ('false_answer_1', models.CharField(max_length=300)),
                ('false_answer_2', models.CharField(max_length=300)),
                ('false_answer_3', models.CharField(max_length=300)),
                ('lesson_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lessons')),
                ('users', models.ManyToManyField(through='course.CompletedQuestions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('module_id', models.IntegerField(primary_key=True, serialize=False)),
                ('module_number', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.courses')),
            ],
        ),
        migrations.AddField(
            model_name='lessons',
            name='module_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.modules'),
        ),
        migrations.AddField(
            model_name='courses',
            name='users',
            field=models.ManyToManyField(through='course.UserCourse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='completedquestions',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.question'),
        ),
        migrations.AddField(
            model_name='completedquestions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
