# Generated by Django 4.2.6 on 2023-11-14 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completedtests',
            options={'verbose_name_plural': 'completed tests'},
        ),
        migrations.AlterModelOptions(
            name='selectedanswers',
            options={'verbose_name_plural': 'selected answers'},
        ),
        migrations.AlterModelTable(
            name='completedtests',
            table='completed_tests',
        ),
        migrations.AlterModelTable(
            name='selectedanswers',
            table='selected_answers',
        ),
    ]
